name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master # Run workflow on push to the 'main' branch

permission:
  content: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: your-custom-domain.com # Optional: Remove if not using a custom domain
